### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by kutec** [taniarascia/taniarascia.com#103]
Hello Tania,

I am exploring Gatsby and found your blog quite impressive. However, I am facing wiered error as mentioned below: 
```
Something went wrong installing the "sharp" module

The specified procedure could not be found.
\\?\E:\workspace\taniarascia.com\node_modules\gatsby-plugin-manifest\node_modules\sharp\build\Release\sharp.node

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues


⠋ load plugins
error Command failed with exit code 1.

```
I tried everything possible with Yarn and NPM package managers. Also removed and re-install sharp. But nothing worked for me.

Can you please help to resolve this issue?

Thanks.

**Comment by taniarascia** [comment]
Hi, you have to lower your Node version to 10 or 11 to resolve this. I've tried for hours to get it work on Node 12 and 13 but no avail.

**Comment by kutec** [comment]
Oh thanks. Let me try with this :)

**Comment by kutec** [comment]
Hi, I tried with `node v10.19.0` but still no luck. Can you share which version of the node do you have where this project run well?

**Comment by willowell** [comment]
**OS: macOS 10.15.1**

Hello Tania,

I encountered the same problem trying to build your website on my computer. I was not able to build your website using Node 13.5.0 because it would error out on trying to build Sharp.

On a hunch, I checked your website for your post about transitioning to Gatsby, and I chose Node 11.11.0 since its release date was close to your post.

Then, I downloaded the zip of your website, and **I successfully rebuilt your website with Node 11.11.0 and yarn 1.21.1.**

Node did not give any errors for Sharp on this version, and `gatsby develop` ran without any errors. Gatsby did give two warnings:
```
warn code block or inline code language not specified in markdown. applying
warn unable to find prism language 'terminal' for highlighting. applying generic
```
Since @kutec was unable to build your website with Node 10.19.0, I also tested that version.
To my surprise, **I was able to build your website with Node 10.19.0 as well**, so @kutec may be encountering a Windows-specific issue. I am not able to test building your website on a Windows machine at this time, so I cannot verify if this is a Windows-specific issue.

**Comment by taniarascia** [comment]
As a note, this warning:

> warn code block or inline code language not specified in markdown. applying warn unable to find prism language 'terminal' for highlighting. applying generic

Is not important - it simply refers to the fact that I've created my own style of code block that is not officially part of prism. (Using ```terminal creates the terminal output).

I have no idea about running this site on Windows.

I'd prefer to have a site that works perfectly fine on the latest version of Node, but I haven't had enough time to delve into it. I tried updating every package and using the latest Node, but that didn't work, and this site works for now so it hasn't been an issue for me.

**Comment by willowell** [comment]
Also, just out of curiosity, I tried building your website with Node 12.16.1, only bumping sharp up to `^0.23.4` in `package.json` before running yarn. 
I was then able to successfully build your website.

This did not work for Node 13.5.0, though.

I cloned a fresh copy of your website each time.

I tried this because Sharp was recently updated to support Node 13: https://sharp.pixelplumbing.com/changelog#v0232---28supthsup-october-2019

I did not make any other changes to `package.json`.

I don't know if you have already tried this, but I hope this information is helpful either way. 

I have no idea why it works with Node 12.16.1 but not 13.5.0. It's even weirder that Sharp's Node 13 update doesn't work with Node 13 for your website.

**Comment by kutec** [comment]
Did you guys noticed that I am getting this error from `gatsby-plugin-manifest`
```
The specified procedure could not be found.
\\?\E:\workspace\taniarascia.com\node_modules\gatsby-plugin-manifest\node_modules\sharp\build\Release\sharp.node
```

**Comment by willowell** [comment]
I have found a solution after some research.
Please see https://github.com/gatsbyjs/gatsby/issues/21032

@kutec `gatsby-plugin-manifest` depends on `sharp`; in order to override this dependency, one has to use yarn resolutions. As you can see [here](https://github.com/gatsbyjs/gatsby/issues/21032#issuecomment-580258601), Gatsby does not yet support the latest version of sharp because it requires Node 10. However, Sharp was recently updated for both Node 13 and libvips.

Here are the steps I took to build your website:
1. Clone a fresh copy of the repository and `cd` into it.

2. Ensure that the current node version is 13.5.0.

3. Delete `yarn.lock`, and replace the dependencies in `package.json` with:
```
"dependencies": {
    "eslint-utils": "^2.0.0",
    "gatsby": "^2.19.21",
    "gatsby-image": "^2.2.41",
    "gatsby-plugin-catch-links": "^2.1.25",
    "gatsby-plugin-feed": "^2.3.27",
    "gatsby-plugin-google-analytics": "^2.1.36",
    "gatsby-plugin-manifest": "^2.2.42",
    "gatsby-plugin-netlify": "^2.1.32",
    "gatsby-plugin-nprogress": "^2.1.19",
    "gatsby-plugin-offline": "^3.0.35",
    "gatsby-plugin-react-helmet": "3.1.22",
    "gatsby-plugin-sass": "^2.1.29",
    "gatsby-plugin-sharp": "2.4.5",
    "gatsby-plugin-sitemap": "2.2.27",
    "gatsby-remark-autolink-headers": "^2.1.24",
    "gatsby-remark-copy-linked-files": "^2.1.37",
    "gatsby-remark-images": "3.1.44",
    "gatsby-remark-prismjs": "3.3.31",
    "gatsby-source-filesystem": "^2.1.48",
    "gatsby-transformer-remark": "2.6.53",
    "gatsby-transformer-sharp": "2.3.14",
    "lodash": "^4.17.15",
    "lodash.kebabcase": "^4.1.1",
    "moment": "^2.24.0",
    "node-sass": "^4.13.1",
    "prismjs": "^1.19.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-github-btn": "^1.1.1",
    "react-helmet": "^5.2.1",
    "url-join": "^4.0.1"
  },
  "resolutions": {
    "sharp": "^0.24.1"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.3",
    "cli-glob": "^0.1.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-config-prettier": "6.10.0",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.18.3",
    "prettier": "^1.19.1",
    "remark-cli": "^7.0.1",
    "remark-preset-lint-recommended": "^3.0.3",
    "stylefmt": "^6.0.3",
    "stylelint": "^13.2.0",
    "stylelint-config-standard": "^20.0.0",
    "write-good": "^1.0.2"
  },
```
I basically just bumped up all of the versions of the packages, and moved `sharp` into a yarn resolutions section.

4. Install the latest version of `libvips` via Homebrew; `brew upgrade libvips` if necessary. See [here](https://github.com/lovell/sharp/issues/2062) for why. While experimenting with the versions, I found that having an up-to-date libvips but not an up-to-date sharp (for instance, in the Gatsby plugin dependencies) caused Gatsby to fail to process PNG files. It might not be important to update libvips this way, but I just did it to be safe.

5. Run `yarn`. Yarn will generate a lot of warnings about `core-js` being deprecated for the Gatsby plugins.

6. Run `gatsby develop`.

7. Voilà!!!
![Screen Shot 2020-02-25 at 4 03 12 AM](https://user-images.githubusercontent.com/9555113/75231617-c3786100-5783-11ea-924e-457d85b7308d.png)

@taniarascia I hope this helps, and most importantly, I hope I have provided enough information for you to be able to reproduce this!

**Comment by taniarascia** [comment]
@willowell Awesome, thanks for looking into that! It makes sense now. I got pretty far along with installing `libvips` and so on, but I didn't investigate which packages were bringing in the old versions. It's annoying that Gatsby is still on Node 8 when we're up to 13 already.

I'm wondering about updating this with CI since I won't be telling CI to have the latest `libvips`, so I'll have to look into that a bit.

Thanks again for looking into it.

**Comment by willowell** [comment]
@taniarascia You're welcome! 😃 I had fun figuring out the solution. 

Your tutorials inspired me to try making my own website with Gatsby and React, so it's the least I can do to help.

Hopefully someone else will benefit from what we found, too.

**Comment by kutec** [comment]
@taniarascia, @willowell great thanks to both of you for looking into this issue. Yet I didn't check on this. I will update once try with the latest solution provided by @willowell. Thanks once again :)

**Comment by kutec** [comment]
@taniarascia, @willowell great thanks to both of you for looking into this issue. Yet I didn't check on this. I will update once try with the latest solution provided by @willowell. Thanks once again :)

**Comment by kutec** [comment]
@willowell, finally... The solution worked for me. I had followed the exact steps shared by you, except #4. Thanks once again for all your efforts for helping :)

Have a great day.
