### ISSUE TITLE
How do you manage your articles?

### ISSUE THREAD

**Issue by kutec** [taniarascia/taniarascia.com#105]
Hi Tania,

I had the impression that your site has Netlify CMS configured for articles. However, I couldn't find anything for the same. May I know the reason for not considering Netlify CMS as your site deployed at Netlify only...

Netlify CMS gives a kind of Admin panel to write/draft/publish articles directly from the browser. In absence of that, do you have other tools for a similar purpose?

Thanks.

**Comment by duncanleung** [comment]
HI @kutec,

You don't need a CMS to act as the source. Gatsby source plugins allows use of normal files (in this case, markdown files) to act as a content source.
You can see this here:
https://github.com/taniarascia/taniarascia.com/blob/master/gatsby-config.js#L36-L41

Gatsby comes built in with a markdown file parser. You can read more here:
https://www.gatsbyjs.org/docs/mdx/markdown-syntax/

All the post content is stored here:
https://github.com/taniarascia/taniarascia.com/tree/master/content/posts

This blog is set up to generate static blog pages from this directory `/content/posts`.

For non developers, using a CMS can be helpful, however, it also adds overhead and complexity since connecting to a CMS also requires maintenance.

Hope this answers your questions.

**Comment by taniarascia** [comment]
Thanks @duncanleung.

**Comment by kutec** [comment]
@duncanleung, thanks.
